// Generated by CoffeeScript 1.8.0
(function() {
  router.on('gimme-json', (function(_this) {
    return function(socket, P, next) {
      var client_id, name, value;
      help('gimme-json');
      name = P[0];
      client_id = _this.get_client_id(null, socket);
      value = {
        'foo': 42,
        'bar': true,
        'client-id': client_id
      };
      socket.emit('heres-json', value);
      return next();
    };
  })(this));

}).call(this);
